config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: 'devise/sessions#new'
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :likes, only: [:create]
      resources :comments, only: %i[new create]
    end
  end
end

app/views/partials/_comments_card.html.erb
<div class="card">
  <div class="card-body">
    <% comments.each do |comment| %>
      <% if comment.author %>
        <p><%= comment.author.name %>: <%= comment.text %></p>
      <% else %>
        <p><%= comment.text %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "BlogApp", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0 nav justify-content-end">
      <% if user_signed_in? %>
       
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout",  users_sign_out_path, class: "nav-link" %>
        </li>
      <% else %>
        
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_post_card.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title"><%= post.title %></h4>
    <div class="text-truncate text-justify"><%= post.text %></div>
    <div class="d-flex justify-content-end gap-1 align-items-end">
      <p class="m-0">Comments: <%= post.comments_counter %>,</p>
      <p class="m-0">Likes: <%= post.likes_counter %></p>
    </div>
  </div>
</div>

app/views/partials/_user_card.html.erb
<div class="d-flex justify-content-between mb-5">
     
  <div class="card avatar-card">
    <img src="<%= user.photo %>" alt="avatar" class="card-img-top" />
  </div>

 <div class="card user-info-card">
   <div class="card-body d-flex justify-content-between">
      <h3 class="card-title m-0"><b><%= user.name %></b></h3>
     <p class="card-text post-number m-0">Number of posts: <%= user.posts_counter %></p>
    </div>
  </div>
</div>