config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: 'devise/sessions#new'
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :likes, only: [:create]
      resources :comments, only: %i[new create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_save :update_posts_counter

  before_validation :set_counter_to_zero

  def set_counter_to_zero
    self.comments_counter = 0 if comments_counter.nil?
    self.likes_counter = 0 if likes_counter.nil?
  end

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def five_recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    per_page = 10
    page = params[:page].to_i
    page = 1 if page <= 0

    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, :comments)
      .order(created_at: :desc)
      .offset((page - 1) * per_page)
      .limit(per_page)

    total_posts = @user.posts.count
    @total_pages = (total_posts.to_f / per_page).ceil
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def new
    @user = User.find(params[:user_id])
    @post = current_user.posts.build
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="container mt-5">
  <%= render partial: 'partials/user_card', locals: { user: @user } %>
  <% if @posts.empty? %>
    <p>This user has no posts yet</p>
  <% end %>
  <% @posts.each do |post| %>
    <a href="/users/<%= post.author.id %>/posts/<%= post.id %>" class="text-decoration-none">
      <div class="mb-4">
        <%= render 'partials/post_card', post: post %>
        <%= render 'partials/comments_card', comments: post.five_recent_comments unless post.five_recent_comments.empty? %>
      </div>
    </a>
  <% end %>
  <nav aria-label="Pagination for posts" class="mt-5">
    <ul class="pagination justify-content-center">
      <% (1..@total_pages).each do |page| %>
        <li class="page-item <%= 'active' if params[:page].to_i == page %>">
          <a class="page-link" href="<%= user_posts_path(@user, page: page) %>"><%= page %></a>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/posts/new.html.erb
<%= form_for([@user, @post]) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control", rows: 4 %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container mt-5">
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="card-title"><%= @post.title %> by <%= @post.author.name %></h4>
      <div class="d-flex gap-1 justify-content-end">
        <p class="m-0">Comments: <%= @post.comments_counter %>,</p>
        <p class="m-0">Likes: <%= @post.likes_counter %></p>
      </div>
      <p class="mt-2"><%= @post.text %></p>

      <%= form_for(@post.likes.new, url: user_post_likes_path(@post.author, @post)) do |f| %>
        <%= f.hidden_field :author_id, value: current_user.id %>
        <%= f.submit "Like", class: "btn btn-primary" %>
      <% end %><br>

      <%= form_for(@post.comments.new, url: user_post_comments_path(@post.author, @post)) do |f| %>
      
        <%= f.text_area :text, placeholder: "Leave a comment..." %>
        <%= f.hidden_field :author_id, value: current_user.id %>
        <%= f.submit "Comment", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <%= render partial: 'partials/comments_card', locals: { comments: @post.comments } unless @post.comments.empty?%>
</div>